name: Publish

on:
  release:
    types: [published]
    branches: [master]
env:
  DOTNET_VERSION: '7.0.x'
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="2facliclient-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish 2FA --runtime "${{ matrix.target }}" -c Release --property:PublishDir="../artifacts" --self-contained false

          # Pack files
          if [[ "${{ matrix.target }}" == win-* ]]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./artifacts/*"
          else
            tar -Cczvf "${release_name}.tar.gz" "./artifacts"
          fi

          # Delete output directory
          rm -r "./artifacts"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            2facliclient*.zip
            2facliclient*.tar.gz
